version: '3'

services:
  pluto:
    image: europe-west3-docker.pkg.dev/hoprassociation/docker-images/hopr-pluto:2.0.0
    hostname: pluto
    platform: linux/amd64
    container_name: pluto
    pull_policy: always
    mem_reservation: 1g
    mem_limit: 4g
    restart: unless-stopped
    volumes:
      - pluto-data:/tmp
    ports:
      # mapping admin and api ports to localhost for app developers to access
      # the admin UI more easily
      - '13301-13305:13301-13305'
      - '19501-19505:19501-19505'
      # local RPC port
      - '8545:8545'
    expose:
      - 13301-13305
    environment:
      - HOPRD_API_TOKEN=${HOPRD_API_TOKEN}
      - HOPRD_HOST=0.0.0.0
volumes:
  # hoprd node identity files
  pluto-data: # exit node identity file
