/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { HoprAddress } from '../models';
import { InlineResponse20010 } from '../models';
import { InlineResponse422 } from '../models';
/**
 * PeerInfoApi - axios parameter creator
 * @export
 */
export const PeerInfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get information about this peer.
         * @param {HoprAddress} peerid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        peerInfoGetPeerInfo: async (peerid: HoprAddress, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'peerid' is not null or undefined
            if (peerid === null || peerid === undefined) {
                throw new RequiredError('peerid','Required parameter peerid was null or undefined when calling peerInfoGetPeerInfo.');
            }
            const localVarPath = `/peerInfo/{peerid}`
                .replace(`{${"peerid"}}`, encodeURIComponent(String(peerid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication keyScheme required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("x-auth-token")
                    : await configuration.apiKey;
                localVarHeaderParameter["x-auth-token"] = localVarApiKeyValue;
            }

            // authentication passwordScheme required
            // http basic authentication required
            if (configuration && (configuration.username || configuration.password)) {
                localVarRequestOptions["auth"] = { username: configuration.username, password: configuration.password };
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PeerInfoApi - functional programming interface
 * @export
 */
export const PeerInfoApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get information about this peer.
         * @param {HoprAddress} peerid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async peerInfoGetPeerInfo(peerid: HoprAddress, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20010>>> {
            const localVarAxiosArgs = await PeerInfoApiAxiosParamCreator(configuration).peerInfoGetPeerInfo(peerid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PeerInfoApi - factory interface
 * @export
 */
export const PeerInfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get information about this peer.
         * @param {HoprAddress} peerid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async peerInfoGetPeerInfo(peerid: HoprAddress, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20010>> {
            return PeerInfoApiFp(configuration).peerInfoGetPeerInfo(peerid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PeerInfoApi - object-oriented interface
 * @export
 * @class PeerInfoApi
 * @extends {BaseAPI}
 */
export class PeerInfoApi extends BaseAPI {
    /**
     * Get information about this peer.
     * @param {HoprAddress} peerid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PeerInfoApi
     */
    public async peerInfoGetPeerInfo(peerid: HoprAddress, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20010>> {
        return PeerInfoApiFp(this.configuration).peerInfoGetPeerInfo(peerid, options).then((request) => request(this.axios, this.basePath));
    }
}
