name: Build

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '22.x'

concurrency:
  group: build-${{ inputs.node_version }}
  cancel-in-progress: false

jobs:
  checks:
    name: Build
    runs-on: depot-ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js
        uses: hoprnet/hopr-workflows/actions/setup-node-js@15db9fb5571957317b77567abef997b1554f2fbb # v1
        with:
          node_version: ${{ inputs.node_version }}
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Building
        run: yarn build
      - name: Linting
        run: yarn lint:ci
      - name: Formatting
        run: yarn format:ci
      - name: Testing
        run: yarn test
