name: Merge PR

on:
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency:
  group: merge
  cancel-in-progress: false

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
  publish:
    name: Publish
    needs: build
    uses: ./.github/workflows/publish.yaml
    with:
      version_type: 'pr'
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      gcp_service_account: ${{ secrets.GCP_SA_GITHUB_RUNNER }}
  docs:
    name: Docs
    needs: build
    runs-on: depot-ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js
        uses: hoprnet/hopr-workflows/actions/setup-node-js@setup-node-js-v1
        with:
          node_version: 22.x
      - name: Create docs
        run: |
          rm -rf docs/*
          yarn docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs
          force_orphan: true

