# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]

jobs:
  general:
    name: CI run (node ${{ matrix.node-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Building
        run: yarn build

      - name: Linting
        run: yarn lint:ci

      - name: Formatting
        run: yarn format:ci

      - name: Testing
        run: yarn test

  # Run E2E tests
  # e2e_testing:
  #   name: E2E tests
  #   needs: general
  #   timeout-minutes: 30
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Node.js environment
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version-file: '.nvmrc'
  #         cache: 'yarn'
  #        cache-dependency-path: ./yarn.lock

  #     - name: Install dependencies
  #       run: yarn --frozen-lockfile

  #     - name: Building
  #       run: yarn build

  #    - name: Run E2E
  #       shell: bash
  #       run: yarn test:e2e
