name: Review

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  # find the branch name for 'pull_request' or on 'push' events
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  review:
    name: Review source code
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: ./yarn.lock
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        shell: bash
        run: yarn

      - name: Build
        shell: bash
        run: yarn build

  # Run publish if pr title includes [RELEASE]
  publish:
    needs: review
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, '[RELEASE]')
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish package
        uses: ./.github/actions/publish
