/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';
import { NativeAddress } from './native-address';
/**
 * 
 * @export
 * @interface AccountWithdrawBody
 */
export interface AccountWithdrawBody {
    /**
     * 
     * @type {Currency}
     * @memberof AccountWithdrawBody
     */
    currency: Currency;
    /**
     * Amount to withdraw in the currency's smallest unit.
     * @type {string}
     * @memberof AccountWithdrawBody
     */
    amount: string;
    /**
     * 
     * @type {NativeAddress}
     * @memberof AccountWithdrawBody
     */
    recipient: NativeAddress;
}
