/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AliasesBody
 */
export interface AliasesBody {
    /**
     * PeerId that we want to set alias to.
     * @type {string}
     * @memberof AliasesBody
     */
    peerId: string;
    /**
     * Alias that we want to attach to peerId.
     * @type {string}
     * @memberof AliasesBody
     */
    alias: string;
}
