/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChannelStatus } from './channel-status';
import { HoprAddress } from './hopr-address';
import { HoprBalance } from './hopr-balance';
/**
 * 
 * @export
 * @interface Channel
 */
export interface Channel {
    /**
     * Channel can be either incomming or outgoing. Incomming means that other node can send messages using this node as relay. Outgoing means that this node can use other node to send message as realy.
     * @type {string}
     * @memberof Channel
     */
    type?: ChannelTypeEnum;
    /**
     * Channel ID that can be used in other calls, not to confuse with transaction hash.
     * @type {string}
     * @memberof Channel
     */
    channelId?: string;
    /**
     * 
     * @type {HoprAddress}
     * @memberof Channel
     */
    peerId?: HoprAddress;
    /**
     * 
     * @type {ChannelStatus}
     * @memberof Channel
     */
    status?: ChannelStatus;
    /**
     * 
     * @type {HoprBalance}
     * @memberof Channel
     */
    balance?: HoprBalance;
}

/**
    * @export
    * @enum {string}
    */
export enum ChannelTypeEnum {
    Incoming = 'incoming',
    Outgoing = 'outgoing'
}

