/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ChannelsBody
 */
export interface ChannelsBody {
    /**
     * PeerId that we want to transact with using this channel.
     * @type {string}
     * @memberof ChannelsBody
     */
    peerId: string;
    /**
     * Amount of HOPR tokens to fund the channel. It will be used to pay for sending messages through channel
     * @type {string}
     * @memberof ChannelsBody
     */
    amount: string;
}
