/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FundmultiBody
 */
export interface FundmultiBody {
    /**
     * PeerId to fund the outgoing/incoming channels with.
     * @type {string}
     * @memberof FundmultiBody
     */
    peerId: string;
    /**
     * Amount of HOPR tokens to fund the outgoing channel (node -> counterparty). It will be used to pay for sending messages through channel
     * @type {string}
     * @memberof FundmultiBody
     */
    outgoingAmount: string;
    /**
     * Amount of HOPR tokens to fund the incoming channel (counterparty -> node). It will be used to pay for sending messages through channel
     * @type {string}
     * @memberof FundmultiBody
     */
    incomingAmount: string;
}
