/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Channel } from './channel';
import { ChannelTopology } from './channel-topology';
/**
 * 
 * @export
 * @interface InlineResponse2005
 */
export interface InlineResponse2005 {
    /**
     * Incomming channels are the ones that were opened by a different node and this node acts as relay.
     * @type {Array<Channel>}
     * @memberof InlineResponse2005
     */
    incoming?: Array<Channel>;
    /**
     * Outgoing channels are the ones that were opened by this node and is using other node as relay.
     * @type {Array<Channel>}
     * @memberof InlineResponse2005
     */
    outgoing?: Array<Channel>;
    /**
     * All the channels indexed by the node in the current network.
     * @type {Array<ChannelTopology>}
     * @memberof InlineResponse2005
     */
    all?: Array<ChannelTopology>;
}
