/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20011
 */
export interface InlineResponse20011 {
    /**
     * Receipt of the closing transaction
     * @type {string}
     * @memberof InlineResponse20011
     */
    receipt?: string;
    /**
     * Current status of the channel
     * @type {string}
     * @memberof InlineResponse20011
     */
    channelStatus?: string;
}
