/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponseMap200
 */
export interface InlineResponseMap200 {
    /**
     * Known Multiaddrs of the node
     * @type {Array<string>}
     * @memberof InlineResponseMap200
     */
    multiaddrs?: Array<string>;
    /**
     * true if peer is allowed to access network, otherwise false
     * @type {boolean}
     * @memberof InlineResponseMap200
     */
    isEligible?: boolean;
}
