/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse206
 */
export interface InlineResponse206 {
    /**
     * Type of data
     * @type {string}
     * @memberof InlineResponse206
     */
    type?: string;
    /**
     * Timestamp in miliseconds
     * @type {number}
     * @memberof InlineResponse206
     */
    timestamp?: number;
    /**
     * The text content
     * @type {string}
     * @memberof InlineResponse206
     */
    content?: string;
}
