/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2012
 */
export interface InlineResponse2012 {
    /**
     * Channel ID that can be used in other calls, not to confuse with transaction hash.
     * @type {string}
     * @memberof InlineResponse2012
     */
    channelId?: string;
    /**
     * Receipt for open channel transaction. Can be used to check status of the smart contract call on blockchain.
     * @type {string}
     * @memberof InlineResponse2012
     */
    receipt?: string;
}
