/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HoprAddress } from './hopr-address';
import { NativeAddress } from './native-address';
/**
 * 
 * @export
 * @interface InlineResponse2009
 */
export interface InlineResponse2009 {
    /**
     * 
     * @type {NativeAddress & any}
     * @memberof InlineResponse2009
     */
    nativeAddress?: NativeAddress & any;
    /**
     * 
     * @type {HoprAddress & any}
     * @memberof InlineResponse2009
     */
    hoprAddress?: HoprAddress & any;
    /**
     * 
     * @type {NativeAddress}
     * @memberof InlineResponse2009
     */
    _native?: NativeAddress;
    /**
     * 
     * @type {HoprAddress}
     * @memberof InlineResponse2009
     */
    hopr?: HoprAddress;
}
