/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HoprAddress } from './hopr-address';
/**
 * 
 * @export
 * @interface InlineResponse2006
 */
export interface InlineResponse2006 {
    /**
     * 
     * @type {HoprAddress}
     * @memberof InlineResponse2006
     */
    alice?: HoprAddress;
    /**
     * 
     * @type {HoprAddress}
     * @memberof InlineResponse2006
     */
    bob?: HoprAddress;
}
