/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse2002Connected } from './inline-response2002-connected';
/**
 * 
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * 
     * @type {Array<InlineResponse2002Connected>}
     * @memberof InlineResponse2002
     */
    connected?: Array<InlineResponse2002Connected>;
    /**
     * 
     * @type {Array<InlineResponse2002Connected>}
     * @memberof InlineResponse2002
     */
    announced?: Array<InlineResponse2002Connected>;
}
