/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MessagesBody
 */
export interface MessagesBody {
    /**
     * The message body which should be sent.
     * @type {string}
     * @memberof MessagesBody
     */
    body: string;
    /**
     * The recipient HOPR peer id, to which the message is sent.
     * @type {string}
     * @memberof MessagesBody
     */
    recipient: string;
    /**
     * The path is ordered list of peer ids through which the message should be sent. If no path is provided, a path which covers the nodes minimum required hops will be determined automatically.
     * @type {Array<string>}
     * @memberof MessagesBody
     */
    path?: Array<string>;
    /**
     * Number of required intermediate nodes. This parameter is ignored if path is set.
     * @type {number}
     * @memberof MessagesBody
     */
    hops?: number;
}
