/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Various settings that affects how this node is interacting with the network.
 * @export
 * @interface Settings
 */
export interface Settings {
    /**
     * Prepends your address to all messages so that receiver of the message can know that you sent that message.
     * @type {boolean}
     * @memberof Settings
     */
    includeRecipient?: boolean;
    /**
     * By default, hoprd runs in **passive** mode, this means that your node will not attempt to open or close any channels automatically. When you set your strategy to **promiscuous** mode, your node will attempt to open channels to a _randomly_ selected group of nodes which you have a healthy connection to. At the same time, your node will also attempt to close channels that are running low on balance or are unhealthy.
     * @type {string}
     * @memberof Settings
     */
    strategy?: SettingsStrategyEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SettingsStrategyEnum {
    Passive = 'passive',
    Promiscuous = 'promiscuous'
}

