/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TokenCapability } from './token-capability';
/**
 * 
 * @export
 * @interface TokensBody
 */
export interface TokensBody {
    /**
     * Capabilities attached to the created token.
     * @type {Array<TokenCapability>}
     * @memberof TokensBody
     */
    capabilities: Array<TokenCapability>;
    /**
     * Lifetime of the token in seconds since creation. Defaults to unlimited lifetime.
     * @type {number}
     * @memberof TokensBody
     */
    lifetime?: number;
    /**
     * Description associated with the token.
     * @type {string}
     * @memberof TokensBody
     */
    description?: string;
}
