/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TokenCapabilityLimitConditions } from './token-capability-limit-conditions';
/**
 * 
 * @export
 * @interface TokenCapabilityLimit
 */
export interface TokenCapabilityLimit {
    /**
     * Limit type
     * @type {string}
     * @memberof TokenCapabilityLimit
     */
    type: string;
    /**
     * 
     * @type {TokenCapabilityLimitConditions}
     * @memberof TokenCapabilityLimit
     */
    conditions?: TokenCapabilityLimitConditions;
}
