/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TokenCapabilityLimit } from './token-capability-limit';
/**
 * 
 * @export
 * @interface TokenCapability
 */
export interface TokenCapability {
    /**
     * Short reference of the operation this capability is tied to.
     * @type {string}
     * @memberof TokenCapability
     */
    endpoint: TokenCapabilityEndpointEnum;
    /**
     * 
     * @type {Array<TokenCapabilityLimit>}
     * @memberof TokenCapability
     */
    limits?: Array<TokenCapabilityLimit>;
}

/**
    * @export
    * @enum {string}
    */
export enum TokenCapabilityEndpointEnum {
    TokensCreate = 'tokensCreate',
    TokensGetToken = 'tokensGetToken',
    TicketsGetStatistics = 'ticketsGetStatistics',
    TicketsRedeemTickets = 'ticketsRedeemTickets',
    TicketsGetTickets = 'ticketsGetTickets',
    SettingsGetSettings = 'settingsGetSettings',
    NodeGetVersion = 'nodeGetVersion',
    NodeStreamWebsocket = 'nodeStreamWebsocket',
    NodePing = 'nodePing',
    NodeGetPeers = 'nodeGetPeers',
    NodeGetMetrics = 'nodeGetMetrics',
    NodeGetInfo = 'nodeGetInfo',
    NodeGetEntryNodes = 'nodeGetEntryNodes',
    MessagesWebsocket = 'messagesWebsocket',
    MessagesSign = 'messagesSign',
    MessagesSendMessage = 'messagesSendMessage',
    MessageSign = 'messageSign',
    ChannelsFundChannels = 'channelsFundChannels',
    ChannelsOpenChannel = 'channelsOpenChannel',
    ChannelsGetChannels = 'channelsGetChannels',
    AliasesSetAlias = 'aliasesSetAlias',
    AliasesGetAliases = 'aliasesGetAliases',
    AccountWithdraw = 'accountWithdraw',
    AccountGetBalances = 'accountGetBalances',
    AccountGetAddresses = 'accountGetAddresses',
    AccountGetAddress = 'accountGetAddress',
    TokensDelete = 'tokensDelete',
    SettingsSetSetting = 'settingsSetSetting',
    PeerInfoGetPeerInfo = 'peerInfoGetPeerInfo',
    ChannelsRedeemTickets = 'channelsRedeemTickets',
    ChannelsGetTickets = 'channelsGetTickets',
    ChannelsGetChannel = 'channelsGetChannel',
    ChannelsCloseChannel = 'channelsCloseChannel',
    AliasesGetAlias = 'aliasesGetAlias',
    AliasesRemoveAlias = 'aliasesRemoveAlias'
}

