/* tslint:disable */
/* eslint-disable */
/**
 * HOPRd Rest API v2
 * This Rest API enables developers to interact with a hoprd node programatically.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: tech@hoprnet.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Limit conditions, if any
 * @export
 * @interface TokenCapabilityLimitConditions
 */
export interface TokenCapabilityLimitConditions {
    /**
     * Upper ceiling. Applies to limit type calls.
     * @type {number}
     * @memberof TokenCapabilityLimitConditions
     */
    max?: number;
}
